Refactor config and move files

diff --git a/config/bash/functions b/config/bash/functions
--- a/config/bash/functions
+++ b/config/bash/functions
@@ -1,3 +1,10 @@
+prepend_path() {
+  if test $# -ne 1; then printf 'invalid args: %s\n' "$funcstack[1]"; exit 1; fi
+
+  local dir_path="$1"
+  export PATH="$dir_path:$PATH"
+}
+
 # Checks for unsynced work in all git repositories in the current directory
 # - Branches without upstreams
 # - Branches ahead of their upstreams
